
language: python

python:
  - { PATH: "{{Python37}}",
      VERSION: 3.7,
      DIST: std,
      PYINT: python3.7,
      LD_LIBRARY_PATH: /usr/local/Python-3.7.2 }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
install:
  - $PYINT -c "from pip._internal import main;main(\"install --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyquickhelper tkinterquickhelper pyensae pymmails pymyinstall pyrsslocal mlstatpy mlinsights jyquickhelper manydataapi skl2onnx onnx onnxruntime --upgrade --extra-index-url=https://pypi.python.org/simple/\".split())"
  - $PYINT -c "from pip._internal import main;main(\"install -r requirements_conda.txt\".split())"
  - $PYINT -c "from pip._internal import main;main(\"install -r requirements.txt\".split())"
  - $PYINT --version
  - $PYINT -c "from pip._internal import main;main([\"freeze\"])"
  - export AUDIODEV=null
  - export SDL_VIDEODRIVER=dummy
  - export SDL_AUDIODRIVER=disk
  - export DISPLAY=localhost:0.0

script:
  - { CMD: "$PYINT -u setup.py unittests -g \".*((http)|(SKIP)|(LONG)|(GUI)|(cvxopt)|(theano)|(code_style)).*\"", NAME: "UT", TIMEOUT: 3600 }  # timeout is 3600 for the documentation
  - { CMD: "$PYINT -u setup.py unittests -e \".*code_style.*\"", NAME: "UT_STYLE" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*(http).*\"", NAME: "UT_HTTP" }
  - { CMD: "$PYINT -u setup.py unittests -e .*LONG.* -g \".*((internet)|(cvxopt)|(notebook_eleves)).*\"", NAME: "UT_LONG", TIMEOUT: 3600 }
  - { CMD: "$PYINT -u setup.py unittests -e .*SKIP.* -g \".*((theano)|(keras)|(deep)|(scraping)|(pythonnet)|(huge)|(web)|(ete3)|(cvxopt)|(students)).*\"", NAME: "UT_SKIP" }
  - { CMD: "$PYINT -u setup.py unittests -e .*_1A_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)).*\"", NAME: "UT_1A" }
  - { CMD: "$PYINT -u setup.py unittests -e .*_2A_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)).*\"", NAME: "UT_2A", TIMEOUT: 3600 }
  - { CMD: "$PYINT -u setup.py unittests -e .*_3A_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)).*\"", NAME: "UT_3A" }
  - { CMD: "$PYINT -u setup.py unittests -e .*_EX_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)).*\"", NAME: "UT_EX", TIMEOUT: 3600 }
  - { CMD: "$PYINT -u setup.py unittests -e .*_GUI_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)).*\"", NAME: "UT_GUI", TIMEOUT: 2400 }
  - { CMD: "$PYINT -u setup.py unittests -e .*scraping.* -g \".*((SKIP)|(theano)|(keras)|(ete3)|(cvxopt)).*\"", NAME: "UT_SCRAPING", TIMEOUT: 3600 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*((huge)).*\"", NAME: "UT_HUGE" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*cvxopt.*\"", NAME: "UT_CVXOPT" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*notebook_eleves.*\"", NAME: "UT_NBELEVE" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*students.*\"", NAME: "UT_STUDENTS" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*internet.*\"", NAME: "UT_INTERNET" }
#  - if [ ${VERSION} == "3.7" and ${DIST} == "std" ]
#      then 
#        --CMD=echo skip unit test;;
#        --NAME=DOC1;;
#        --CLEAN=0;;
#        --TIMEOUT=5400;;
#      fi
#  - if [ ${VERSION} == "3.7" and ${DIST} == "std" ]
#      then 
#        --CMD=echo skip unit test;;
#        --NAME=DOC3;;
#        --CLEAN=0;;
#        --TIMEOUT=5400;;
#      fi

after_script:
  - $PYINT -u setup.py bdist_wheel
  - if [ ${VERSION} == "3.7" and ${DIST} != "conda" and ${NAME} == "UT" ] then cp dist/*.whl {{root_path}}/../local_pypi/local_pypi_server fi

documentation:
  # The first run of the documentation may fail, the second goes one.
  - if [ ${NAME} == "UT" ] then $PYINT -u setup.py build_sphinx > sphinx_doc.log 2>&1 fi
  - if [ ${NAME} == "DOC1" ] then python -u setup.py build_sphinx html1 > sphinx_doc1.log 2>&1 fi
  - if [ ${NAME} == "DOC3" ] then python -u setup.py build_sphinx html3 > sphinx_doc3.log 2>&1 fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build/html dist/html fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build3/html dist/html3 fi
  - if [ ${NAME} == "DOC1" ] then cp -R -f _doc/sphinxdoc/build/html dist/html fi
  - if [ ${NAME} == "DOC3" ] then cp -R -f _doc/sphinxdoc/build3/html dist/html3 fi
