language: python
python:
  - { PATH: "{{replace(Python35, '\\', '\\\\')}}", VERSION: 3.5, DIST: std }
  - { PATH: "{{replace(Python36, '\\', '\\\\')}}", VERSION: 3.6, DIST: std }
  - { PATH: "{{replace(Anaconda3, '\\', '\\\\')}}", VERSION: 3.6, DIST: conda }
  - { PATH: "{{replace(WinPython36, '\\', '\\\\')}}", VERSION: 3.6, DIST: winpython }
virtualenv:
  - path: {{ospathjoin(root_path, pickname("%NAME_JENKINS%", project_name + "_%VERSION%_%DIST%_%NAME%"), "_venv")}}
install:
  - pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyquickhelper tkinterquickhelper pyensae pymmails pymyinstall pyrsslocal mlstatpy
  - pip install -r requirements.txt
  - pip freeze
  - pip freeze > pip_freeze.txt
before_script:
  - python -u setup.py try_import
  - set KERAS_BACKEND=theano
script:
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests", NAME: "UT", TIMEOUT: 3600 }  # timeout is 3600 for the documentation
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests_LONG", NAME: "UT_LONG", TIMEOUT: 3600 }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e .*SKIP.* -g \".*((theano)|(keras)|(deep)|(scraping)).*\"", NAME: "UT_SKIP" }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e .*_1A_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)).*\"", NAME: "UT_1A" }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e .*_2A_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)).*\"", NAME: "UT_2A", TIMEOUT: 3600 }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e .*_3A_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)).*\"", NAME: "UT_3A" }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e .*_EX_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)).*\"", NAME: "UT_EX", TIMEOUT: 3600 }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e .*_GUI_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)).*\"", NAME: "UT_GUI", TIMEOUT: 2400 }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e .*scraping.* -g \".*((SKIP)|(theano)|(keras)).*\"", NAME: "UT_SCRAPING", TIMEOUT: 3600 }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e \".*((theano)|(keras)).*\"", NAME: "UT_DEEP", TIMEOUT: 2400 }
  - if [ ${VERSION} == "3.5" and ${DIST} == "std" ]
      then 
        --CMD=python -u setup.py build_sphinx;
        --NAME=DOC;
      fi  
after_script:
  - python -u setup.py bdist_wheel
  - if [ ${DIST} != "conda" and ${VERSION} == "3.5" and ${NAME} == "UT" ] then copy dist\*.whl {{root_path}}\..\..\..\local_pypi\local_pypi_server fi
documentation:
  - if [ ${NAME} in {"UT", "DOC"} ] then python -u setup.py build_pres fi
  - if [ ${NAME} in {"UT", "DOC"} ] then python -u setup.py build_pres_2A fi
  - if [ ${NAME} in {"UT", "DOC"} ] then python -u setup.py build_pres_3A fi
  - if [ ${NAME} in {"UT", "DOC"} ] then python -u setup.py build_pres_1Ap fi
  - if [ ${NAME} == "UT" ] then python -u setup.py build_sphinx fi
  - if [ ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\sphinxdoc\build\html dist\html fi
  - if [ ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\sphinxdoc\build2\html dist\html2 fi
  - if [ ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\sphinxdoc\build3\html dist\html3 fi
  - if [ ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation_projets\a2015\build\html dist\html_pres_1Ap\2015 fi
  - if [ ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation_projets\a2016\build\html dist\html_pres_1Ap fi
  - if [ ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation_2A\build\html dist\html_pres_2A fi
  - if [ ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation_3A\build\html dist\html_pres_3A fi
  - if [ ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation\build\html dist\html_pres fi
